import { DeleteWorkItemButton } from './DeleteWorkItemButton';
import { Input, NativeSelect, Textarea } from '../ui';
import { useState } from 'react';
import type { CollaborationDatabase, CollaborationWorkItem } from '../../domain/collaboration';
import { MarkdownMessage } from '../common/MarkdownMessage';
export function ProjectItemDetail({item,database,onUpdate,onClose,onDelete}:{item:CollaborationWorkItem;onDelete:(id:string)=>void;database:CollaborationDatabase;onUpdate:(id:string,patch:Partial<CollaborationWorkItem>)=>Promise<void>;onClose:()=>void}) {
 const [editing,setEditing]=useState(false);
 return <aside aria-label="工作项详情" className="project-item-detail"><header className="mb-6 flex items-center justify-between text-xs text-slate-500"><span className="flex-1">工作项详情</span><DeleteWorkItemButton title={item.title} onClick={()=>onDelete(item.id)}/><button type="button" aria-label="关闭工作项详情" onClick={onClose}>✕</button></header><Input key={item.title} aria-label="工作项标题" defaultValue={item.title} className="mb-6 w-full bg-transparent text-2xl font-bold outline-none" onBlur={e=>{const title=e.target.value.trim();if(title&&title!==item.title)void onUpdate(item.id,{title});else e.target.value=item.title}}/>
 <div className="space-y-3 text-xs"><label className="detail-property">状态<NativeSelect aria-label="工作项状态" value={item.statusId} onChange={e=>void onUpdate(item.id,{statusId:e.target.value})}>{database.statuses.map(status=><option key={status.id} value={status.id}>{status.name}</option>)}</NativeSelect></label><label className="detail-property">优先级<NativeSelect aria-label="工作项优先级" value={item.priorityId} onChange={e=>void onUpdate(item.id,{priorityId:e.target.value})}>{database.priorities.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</NativeSelect></label><label className="detail-property">负责人<NativeSelect aria-label="工作项负责人" value={item.assigneeIds[0]??''} onChange={e=>void onUpdate(item.id,{assigneeIds:e.target.value?[e.target.value]:[]})}><option value="">未指派</option>{database.assignees.map(a=><option key={a.id} value={a.id}>{a.displayName}</option>)}</NativeSelect></label><label className="detail-property">开始日期<Input aria-label="工作项开始日期" type="date" value={item.startDate??''} onChange={e=>void onUpdate(item.id,{startDate:e.target.value||undefined})}/></label><label className="detail-property">截止日期<Input aria-label="工作项截止日期" type="date" value={item.dueDate??''} onChange={e=>void onUpdate(item.id,{dueDate:e.target.value||undefined})}/></label></div>
 <div className="mt-7 border-t border-slate-100 pt-5"><div className="mb-3 flex items-center justify-between text-xs font-semibold"><span>说明与下一步</span><button type="button" onClick={()=>setEditing(!editing)} className="text-sky-700">{editing?'预览':'编辑'}</button></div>{editing?<Textarea key={item.id} autoFocus aria-label="工作项正文" defaultValue={item.description} placeholder="记录当前状态、下一步或任务清单（支持 Markdown）" className="min-h-64 w-full resize-y p-3 text-sm leading-6" onBlur={e=>{if(e.target.value!==item.description)void onUpdate(item.id,{description:e.target.value})}}/>:<div className="min-h-32 text-sm leading-6 text-slate-600" onDoubleClick={()=>setEditing(true)}>{item.description?<MarkdownMessage>{item.description}</MarkdownMessage>:<button type="button" onClick={()=>setEditing(true)} className="text-slate-400">添加说明、下一步或任务清单…</button>}</div>}</div></aside>;
}
